# Generated by Django 3.1.2 on 2022-09-07 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=255, verbose_name='Описание датчика')),
            ],
        ),
        migrations.RenameField(
            model_name='measurement',
            old_name='value',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AddField(
            model_name='sensor',
            name='measurements',
            field=models.ManyToManyField(related_name='measurements', to='measurements.Measurement'),
        ),
    ]
